max_simultaneous = 10_000
refresh_delay = 0.01
start_method = 'spawn'

[recipe.recipe1]
ingredient = 'b'
path = "/Users/jhughes/Desktop/repos/mestolo/recipes.py"
priority = 10
trigger = false
delay = 0.01
escalation_times = [5, 10, 15]
escalation_values = [20, 30, 50]
inputs = []
valid_before_seconds = 10


[recipe.recipe2]
ingredient = 'c'
path = "/Users/jhughes/Desktop/repos/mestolo/recipes.py"
priority = 0
trigger = false
delay = 3
escalation_times = [5, 20]
escalation_values = [1, 2]
inputs = []
valid_before_seconds = 10


[recipe.recipe3]
ingredient = 'd'
path = "/Users/jhughes/Desktop/repos/mestolo/recipes.py"
priority = 100
trigger = false
delay = 5
escalation_times = [15]
escalation_values = [500]
inputs = ['b', 'c']
valid_before_seconds = 10
